#!/usr/bin/env python3
"""
nan_to_mcp.py
~~~~~~~~~~~~~
Converts Nan's async tool modules (PythonScripts_TCToolbox style) into
FastMCP @mcp.tool() functions compatible with invest-mcp/server.py.

Handles every pattern found across Nan's 29 tool files:

  Pattern 1 – Direct required param
      invest_args["key"] = params["key"]
      → def run_xxx(key: str, ...)

  Pattern 2 – Optional with default (.get)
      invest_args["key"] = params.get("key", default)
      → def run_xxx(key: str = "default", ...)

  Pattern 3 – Cast wrapper on required param
      invest_args["key"] = int(params["key"])
      → def run_xxx(key: int, ...)

  Pattern 4 – Local variable (traces back to .get)
      cc_method = params.get("cc_method", "factors")
      invest_args["cc_method"] = cc_method
      → def run_xxx(cc_method: str = "factors", ...)

  Pattern 5 – Conditional block addition
      if snap_points:
          invest_args["flow_threshold"] = params.get("flow_threshold", 1000)
      → def run_xxx(flow_threshold: int = 1000, ...)   (always included, InVEST ignores extra keys)

  Key renames (scenic_quality: "aoi_path" ← params["aoi_vector_path"])
      → uses INVEST key as function param name so no remapping needed

Usage
-----
    # Preview generated code for one module (stdout)
    python nan_to_mcp.py path/to/coastal_vulnerability.py

    # Convert all new tools and write to a file
    python nan_to_mcp.py path/to/tools/ --output new_tools.py

    # Append only tools NOT already in server.py
    python nan_to_mcp.py path/to/tools/ --append-to server.py

    # Dry-run: show which files would be converted
    python nan_to_mcp.py path/to/tools/ --dry-run

    # Explicitly skip certain modules
    python nan_to_mcp.py path/to/tools/ --skip cbc_main cbc_preprocessor habitat_quality
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Official InVEST docs cache  (generated by fetch_invest_docs.py)
# Structure: {function_name: {"description": str, "params": {key: desc}}}
# ---------------------------------------------------------------------------
_DOCS_CACHE_PATH = Path(__file__).parent / "invest_docs_cache.json"

def _load_docs_cache() -> dict:
    if _DOCS_CACHE_PATH.exists():
        try:
            return json.loads(_DOCS_CACHE_PATH.read_text())
        except Exception:
            pass
    return {}

INVEST_DOCS: dict = _load_docs_cache()


# ---------------------------------------------------------------------------
# Tools already implemented in Shubham's server.py (by function name).
# Used by --append-to to skip duplicates automatically.
# ---------------------------------------------------------------------------
ALREADY_IN_SERVER: set[str] = {
    "run_coastal_blue_carbon_preprocessor",
    "run_coastal_blue_carbon",
    "run_habitat_quality",
    "run_sediment_delivery_ratio",
    "run_nutrient_delivery_ratio",
    "run_seasonal_water_yield",
    "run_annual_water_yield",
    "run_forest_carbon_edge_effect",
    "run_carbon_storage",
    "run_crop_production_percentile",
    "run_crop_production_regression",
    "run_pollination",
    "run_habitat_risk_assessment",
    "run_recreation",
    # tools added manually (non-InVEST)
    "run_network_analysis",
}

# All tools are now auto-generated — custom non-InVEST tools get async wrappers.
NON_INVEST_STUBS: set[str] = set()


# ---------------------------------------------------------------------------
# Parameter description lookup
# Covers ~70 common InVEST parameter names → human-readable description
# matching Shubham's docstring style.  Keys are invest_args dict keys.
# ---------------------------------------------------------------------------
_PARAM_DESCRIPTIONS: dict[str, str] = {
    # ── Universal ────────────────────────────────────────────────────────────
    "workspace_dir":                       "Output directory (auto-created if empty)",
    "results_suffix":                      "Suffix appended to all output filenames",
    # ── DEM / hydrology ──────────────────────────────────────────────────────
    "dem_path":                            "Path to Digital Elevation Model (DEM) raster",
    "dem_raster_path":                     "Path to Digital Elevation Model (DEM) raster",
    "algorithm":                           "Flow routing algorithm: 'D8' (single direction) or 'MFD' (multiple flow direction)",
    "threshold_flow_accumulation":         "Minimum flow accumulation to define a stream pixel",
    "calculate_flow_direction":            "If True, compute flow direction raster",
    "calculate_flow_accumulation":         "If True, compute flow accumulation raster",
    "calculate_stream_threshold":          "If True, compute streams above threshold_flow_accumulation (requires threshold_flow_accumulation)",
    "calculate_slope":                     "If True, compute slope raster",
    "calculate_stream_order":              "If True, compute Strahler stream order raster",
    "calculate_downstream_distance":       "If True, compute downstream distance-to-stream raster",
    "outlet_vector_path":                  "Path to outlet points vector (alternative to detect_pour_points=True)",
    "detect_pour_points":                  "If True, automatically detect pour points from the DEM instead of using outlet_vector_path",
    "snap_points":                         "If True, snap outlet points to the nearest stream pixel",
    "flow_threshold":                      "Minimum flow accumulation to define a stream (used when snap_points=True)",
    "snap_distance":                       "Maximum distance in pixels to snap outlet points to stream (used when snap_points=True)",
    # ── Land cover / biophysical ──────────────────────────────────────────────
    "lulc_path":                           "Path to land use/land cover raster",
    "lulc_raster_path":                    "Path to land use/land cover raster",
    "lulc_cur_path":                       "Path to current land use/land cover raster",
    "lulc_fut_path":                       "Path to future land use/land cover raster (optional)",
    "biophysical_table_path":              "Path to biophysical table CSV mapping LULC codes to model parameters",
    "biophysical_table":                   "Path to biophysical table CSV mapping LULC codes to model parameters",
    # ── Watersheds / AOI ─────────────────────────────────────────────────────
    "watersheds_path":                     "Path to watersheds vector (shapefile or GeoPackage)",
    "aoi_path":                            "Path to area of interest vector",
    "aoi_vector_path":                     "Path to area of interest vector",
    "aoi_watersheds_path":                 "Path to watershed area of interest vector",
    "admin_boundaries_vector_path":        "Path to administrative boundaries vector for result aggregation",
    # ── Climate / hydro inputs ────────────────────────────────────────────────
    "precipitation_path":                  "Path to annual precipitation raster (mm)",
    "eto_path":                            "Path to reference evapotranspiration raster (mm/yr)",
    "ref_eto_raster_path":                 "Path to reference evapotranspiration raster (mm)",
    "soil_group_path":                     "Path to soil hydrologic group raster (1=A, 2=B, 3=C, 4=D)",
    "soils_hydrological_group_raster_path":"Path to soil hydrologic group raster (1=A, 2=B, 3=C, 4=D)",
    # ── Carbon / blue carbon ─────────────────────────────────────────────────
    "landcover_snapshot_csv":              "Path to CSV mapping snapshot years to LULC raster paths (columns: snapshot_year, raster_path)",
    "landcover_transitions_table":         "Path to transition matrix CSV defining disturbance types between LULC class pairs",
    "analysis_year":                       "Final analysis year to extend beyond last snapshot (0 = use last snapshot year only)",
    "do_economic_analysis":                "If True, run net present value (NPV) economic analysis on sequestered carbon",
    "use_price_table":                     "If True, use a yearly price table instead of a fixed price + inflation rate",
    "price_table_path":                    "Path to yearly CO2E price table CSV (required when use_price_table=True)",
    "price":                               "Price of CO2E at the baseline year (currency per metric ton)",
    "discount_rate":                       "Annual discount rate applied to future carbon value (percent)",
    "inflation_rate":                      "Annual rate of increase in CO2E price (percent)",
    # ── Coastal / marine ─────────────────────────────────────────────────────
    "bathymetry_path":                     "Path to bathymetry raster (negative values = depth below sea level, meters)",
    "bathymetry_raster_path":              "Path to bathymetry raster (negative values = depth below sea level, meters)",
    "aoi_vector_path":                     "Path to area of interest vector (optional; clips analysis extent)",
    "dem_averaging_radius":                "Radius in DEM cells over which to smooth elevation values",
    "geomorphology_fill_value":            "Fill value for shoreline segments with missing geomorphology rank",
    "geomorphology_vector_path":           "Path to geomorphology vector with exposure rank attributes per shoreline segment",
    "landmass_vector_path":                "Path to global land polygon vector",
    "max_fetch_distance":                  "Maximum fetch distance for wave exposure calculation (meters)",
    "model_resolution":                    "Spatial resolution for coastal model computations (meters)",
    "wwiii_vector_path":                   "Path to WAVEWATCH III wave-watch data vector",
    "habitat_table_path":                  "Path to habitat protection table CSV (optional; defines rank per habitat type)",
    "shelf_contour_vector_path":           "Path to continental shelf contour vector (optional)",
    "slr_vector_path":                     "Path to sea level rise scenarios vector (optional)",
    "population_raster_path":              "Path to population density raster (optional; used for exposure index)",
    "population_radius":                   "Radius for aggregating population around shoreline segments (meters)",
    "slr_field":                           "Attribute field name in slr_vector_path containing sea level rise values",
    # ── Scenic quality ────────────────────────────────────────────────────────
    "structure_path":                      "Path to viewshed structure vector (e.g. wind turbines, cell towers)",
    "refraction":                          "Atmospheric refractivity coefficient for light bending (default 0.13)",
    "valuation_function":                  "Valuation function type: 'linear', 'logarithmic', 'exponential', or 'polynomial'",
    "a_coef":                              "Coefficient 'a' in the scenic quality valuation function",
    "b_coef":                              "Coefficient 'b' in the scenic quality valuation function",
    "max_valuation_radius":                "Maximum distance from structures for scenic valuation (meters; empty = no limit)",
    # ── Urban cooling ─────────────────────────────────────────────────────────
    "t_ref":                               "Reference (rural) air temperature during the hottest period (°C)",
    "uhi_max":                             "Maximum urban heat island effect — temperature difference urban minus rural (°C)",
    "green_area_cooling_distance":         "Distance over which green areas exert a cooling influence (meters)",
    "cc_method":                           "Cooling capacity method: 'factors' (weighted CC indices) or 'intensity' (NDVI-based)",
    "t_air_average_radius":                "Radius used to spatially average air temperature across pixels (meters)",
    "building_vector_path":                "Path to building footprint vector (optional; required for energy valuation)",
    "avg_rel_humidity":                    "Average relative humidity during the hottest period (percent, 0–100)",
    "energy_consumption_table_path":       "Path to energy consumption table CSV (optional; maps building type to kWh/°C)",
    "do_energy_valuation":                 "If True, calculate energy savings attributable to urban cooling",
    "do_productivity_valuation":           "If True, calculate work productivity gains from reduced heat exposure",
    "cc_weight_shade":                     "Weight for shade contribution to cooling capacity (0–1; weights must sum to 1)",
    "cc_weight_albedo":                    "Weight for albedo contribution to cooling capacity (0–1)",
    "cc_weight_eti":                       "Weight for evapotranspiration contribution to cooling capacity (0–1)",
    # ── Urban flood ───────────────────────────────────────────────────────────
    "rainfall_depth":                      "Depth of the 24-hour design storm rainfall event (mm)",
    "curve_number_table_path":             "Path to curve number table CSV mapping LULC codes to CN values per soil group",
    "built_infrastructure_vector_path":    "Path to built infrastructure vector (optional; enables damage calculation)",
    "infrastructure_damage_loss_table_path":"Path to damage-loss function table CSV (optional; required with infrastructure vector)",
    # ── Urban stormwater ──────────────────────────────────────────────────────
    "adjust_retention_ratios":             "If True, reduce retention ratios near roads (requires retention_radius and road_centerlines_path)",
    "retention_radius":                    "Radius around roads over which retention ratios are adjusted (meters)",
    "road_centerlines_path":               "Path to road centerlines vector (required when adjust_retention_ratios=True)",
    "aggregate_areas_path":                "Path to aggregation areas vector for watershed-level summary statistics (optional)",
    "replacement_cost":                    "Replacement cost of stormwater retention infrastructure (currency per m³; optional)",
    # ── Urban nature access ───────────────────────────────────────────────────
    "lulc_attribute_table":                "Path to LULC attribute CSV defining which classes count as urban nature and their supply",
    "search_radius_mode":                  "Search radius strategy: 'uniform radius', 'radius per population group', or 'radius per urban nature class'",
    "decay_function":                      "Distance decay function for nature access: 'exponential' or 'power'",
    "search_radius":                       "Uniform search radius in meters (required when search_radius_mode='uniform radius')",
    "population_group_radii_table":        "Path to CSV mapping population group field names to search radii (required for 'radius per population group' mode)",
    # ── Wave energy ───────────────────────────────────────────────────────────
    "wave_base_data_path":                 "Path to wave base data directory (contains WAVEWATCH III global wave data)",
    "analysis_area":                       "Named analysis area string (e.g. 'West Coast of North America and Hawaii')",
    "machine_perf_path":                   "Path to wave energy machine performance table CSV (capture width vs. period/height)",
    "machine_param_path":                  "Path to wave energy machine parameters CSV (dimensions, rated capacity)",
    "machine_econ_path":                   "Path to wave energy machine economic parameters CSV (required for valuation)",
    "grid_points_path":                    "Path to grid connection points vector (required for wave/wind energy valuation)",
    "number_of_machines":                  "Number of wave energy machines to place in the analysis area",
    # ── Wind energy ───────────────────────────────────────────────────────────
    "wind_data_path":                      "Path to wind energy data points CSV or vector (contains Weibull wind speed parameters)",
    "global_wind_parameters_path":         "Path to global wind energy parameters CSV (turbine and financial defaults)",
    "land_polygon_vector_path":            "Path to land polygon vector used to compute distance-to-shore",
    "number_of_turbines":                  "Number of turbines to install in the offshore wind farm",
    "turbine_parameters_path":             "Path to turbine parameters CSV (hub height, rotor radius, rated capacity)",
    "avg_grid_distance":                   "Average distance to grid connection point (km; default 4)",
    "max_depth":                           "Maximum water depth for turbine installation (meters; default 60)",
    "max_distance":                        "Maximum distance from shore for turbine siting (meters; default 200 000)",
    "min_depth":                           "Minimum water depth for turbine installation (meters; default 3)",
    "min_distance":                        "Minimum distance from shore for turbine siting (meters; default 0)",
    "valuation_container":                 "If True, run economic valuation (requires foundation_cost, dollar_per_kWh, grid_points_path, land_points_path)",
    # ── Scenario generation ───────────────────────────────────────────────────
    "base_lulc_path":                      "Path to base land use/land cover raster to modify",
    "replacement_lucode":                  "LULC integer code to assign to converted pixels",
    "area_to_convert":                     "Total area to convert from convertible to replacement LULC (hectares)",
    "focal_landcover_codes":               "Space-separated integer LULC codes defining the focal/reference landcover",
    "convertible_landcover_codes":         "Space-separated integer LULC codes eligible for conversion",
    "convert_nearest_to_edge":             "If True, convert pixels nearest to the focal landcover edge first",
    "convert_farthest_from_edge":          "If True, convert pixels farthest from the focal landcover edge first",
    "n_workers":                           "Number of parallel worker processes (optional; -1 = use all cores)",
}


# ---------------------------------------------------------------------------
# Docstring extraction from Nan's module-level docstrings
# ---------------------------------------------------------------------------

def _parse_module_docstring(docstring: str) -> tuple[str, dict[str, str]]:
    """Parse Nan's module docstring into (description, param_hints).

    Input format:
        Tool: <Name> (<module>).

        <optional free-text description>

        Required: key1, key2, ...
        Optional: key1 (hint), key2 (hint), ...
        - special notes ...

    Returns:
        description : multi-sentence string to use as the function summary
        param_hints : {param_name: hint_string} extracted from Optional: lines
    """
    if not docstring:
        return "", {}

    lines = docstring.splitlines()
    desc_lines: list[str] = []
    optional_text_parts: list[str] = []
    in_optional = False

    for line in lines:
        stripped = line.strip()
        # Skip the "Tool: X (module)." header line
        if stripped.startswith("Tool:") or stripped.startswith("Tool "):
            continue
        # Start of Required: section — stop collecting description
        if re.match(r"Required\s*:", stripped, re.IGNORECASE):
            in_optional = False
            continue
        # Start of Optional: section
        if re.match(r"Optional\s*:", stripped, re.IGNORECASE):
            in_optional = True
            # Grab text after "Optional:"
            rest = re.sub(r"^Optional\s*:", "", stripped, flags=re.IGNORECASE).strip()
            if rest:
                optional_text_parts.append(rest)
            continue
        # Continuation of Optional: (indented or bullet)
        if in_optional:
            if stripped.startswith("-") or stripped.startswith("If ") or stripped.startswith("At least"):
                # End structured optional params, but keep as notes
                in_optional = False
            else:
                optional_text_parts.append(stripped)
            continue
        # Regular description lines
        if stripped:
            desc_lines.append(stripped)

    # Build description string — join non-empty lines
    description = " ".join(desc_lines).strip()

    # Parse optional param hints from collected optional text
    # e.g. "cc_method ('factors'|'intensity'), t_air_average_radius, ..."
    # e.g. "avg_grid_distance (km, default 4), max_depth (m, default 60),"
    param_hints: dict[str, str] = {}
    full_optional = " ".join(optional_text_parts)
    # Split on comma, but NOT commas inside parentheses
    # Simple approach: split on ", " followed by a word char
    tokens = re.split(r",\s*(?=[a-z_])", full_optional)
    for token in tokens:
        token = token.strip().rstrip(",. ")
        if not token:
            continue
        # Match: param_name (hint text) or param_name=value or just param_name
        m = re.match(r"^([a-z_][a-z0-9_]*)\s*(.*)$", token)
        if not m:
            continue
        pname = m.group(1)
        hint_raw = m.group(2).strip()
        # Clean up hint: strip outer parens if present
        if hint_raw.startswith("(") and hint_raw.endswith(")"):
            hint_raw = hint_raw[1:-1].strip()
        if hint_raw:
            param_hints[pname] = hint_raw
        else:
            param_hints[pname] = ""   # present but no hint

    return description, param_hints


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class ToolParam:
    name: str         # function parameter name (= invest key)
    type_hint: str    # "str" | "int" | "float" | "bool"
    default: Any      # None means required (no default)
    required: bool


@dataclass
class ToolSpec:
    function_name: str       # e.g. "run_coastal_vulnerability"
    model_name: str          # e.g. "Coastal Vulnerability"
    output_subdir: str       # e.g. "coastal_vulnerability"
    invest_module: str       # e.g. "natcap.invest.coastal_vulnerability" (empty for custom tools)
    invest_execute: str      # e.g. "natcap.invest.coastal_vulnerability.execute"
    params: list[ToolParam]
    doc_summary: str         # first line of module docstring (after "Tool:")
    doc_description: str     # free-text description extracted from module docstring
    doc_param_hints: dict[str, str]  # per-param hints from Optional: section
    source_file: str         # original filename for comments
    has_complex_logic: bool = False
    is_custom_tool: bool = False   # True for non-InVEST tools (async wrapper pattern)


# ---------------------------------------------------------------------------
# Type inference helpers
# ---------------------------------------------------------------------------

_STR_SUFFIXES = (
    "_path", "_csv", "_dir", "_table", "_vector", "_raster", "_suffix",
    "_file", "_shp", "_tif", "_url", "_name", "_eq", "_type", "_zone",
    "_polygon", "_function",
)
_INT_KEYWORDS = (
    "year", "threshold", "n_nearest", "resolution", "max_rating",
    "port", "n_workers", "n_points", "num_", "radius", "distance",
    "fill_value", "accumulation",
)
_FLOAT_KEYWORDS = (
    "rate", "constant", "factor", "param", "fraction", "ratio",
    "price", "discount", "alpha", "beta", "gamma", "size",
    "weight", "depth", "height", "length", "coefficient", "refraction",
    "t_ref", "uhi_max", "humidity", "coef",
)
_BOOL_PREFIXES = (
    "do_", "use_", "calc_", "calculate_", "compute_", "monthly_",
    "user_defined_", "grid_", "visualize_", "is_", "has_", "detect_",
    "snap_",
)


def _infer_type(key: str, default: Any) -> str:
    """Infer Python type annotation from default value first, then key name."""
    if isinstance(default, bool):
        return "bool"
    if isinstance(default, int):
        return "int"
    if isinstance(default, float):
        return "float"
    if isinstance(default, str):
        return "str"
    k = key.lower()
    for p in _BOOL_PREFIXES:
        if k.startswith(p):
            return "bool"
    for s in _STR_SUFFIXES:
        if k.endswith(s):
            return "str"
    for kw in _INT_KEYWORDS:
        if kw in k:
            return "int"
    for kw in _FLOAT_KEYWORDS:
        if kw in k:
            return "float"
    return "str"


def _default_repr(t: str, original: Any) -> str:
    """Render a default value as Python source code."""
    if original is not None:
        if isinstance(original, bool):
            return str(original)
        if isinstance(original, str):
            if original == "":
                return '""'
            return f'"{original}"'
        if isinstance(original, (int, float)):
            return str(original)
    # Fallback per type
    return {"bool": "False", "int": "0", "float": "0.0", "str": '""'}[t]


# ---------------------------------------------------------------------------
# AST helpers
# ---------------------------------------------------------------------------

def _const(node) -> Optional[Any]:
    """Extract scalar constant from AST node, handling negation."""
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        if isinstance(node.operand, ast.Constant):
            return -node.operand.value
    return None


def _cast_name(node) -> Optional[str]:
    """Return 'int', 'float', or 'bool' if node is a cast call; else None."""
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
        if node.func.id in ("int", "float", "bool"):
            return node.func.id
    return None


def _is_params_subscript(node) -> bool:
    """True if node is params["key"] or params[key]."""
    return (
        isinstance(node, ast.Subscript)
        and isinstance(node.value, ast.Name)
        and node.value.id == "params"
    )


def _is_params_get(node) -> bool:
    """True if node is params.get(...)."""
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "get"
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id == "params"
    )


def _extract_params_get(node) -> tuple[str, Any]:
    """From params.get("key", default) return (key, default). default=None if absent."""
    key = _const(node.args[0]) if node.args else None
    default = _const(node.args[1]) if len(node.args) >= 2 else None
    return key, default


# ---------------------------------------------------------------------------
# Per-file extraction
# ---------------------------------------------------------------------------

def _extract_required_keys(tree: ast.Module) -> list[str]:
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "REQUIRED_KEYS":
                    if isinstance(node.value, ast.List):
                        return [
                            elt.value
                            for elt in node.value.elts
                            if isinstance(elt, ast.Constant)
                        ]
    return []


def _extract_invest_module(tree: ast.Module) -> tuple[str, str]:
    """Return (dotted_module, execute_expression) for the natcap.invest call."""
    candidates: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if "natcap.invest" in alias.name:
                    candidates.append(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module and "natcap.invest" in node.module:
                candidates.append(node.module)
    if not candidates:
        return "", ""
    module = candidates[0]
    # Find the .execute(...) call to know the exact callable path
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Attribute) and func.attr == "execute":
                # Reconstruct dotted name
                parts = []
                cur = func.value
                while isinstance(cur, ast.Attribute):
                    parts.append(cur.attr)
                    cur = cur.value
                if isinstance(cur, ast.Name):
                    parts.append(cur.id)
                parts.reverse()
                execute_path = ".".join(parts) + ".execute"
                return module, execute_path
    return module, module + ".execute"


def _collect_local_param_vars(func_body: list) -> dict[str, tuple[str, Any]]:
    """
    Find assignments like:
        cc_method = params.get("cc_method", "factors")
        calc_slope = bool(params.get("calculate_slope", False))
    Returns {var_name: (type_hint, default_value)}.
    """
    result: dict[str, tuple[str, Any]] = {}
    for stmt in func_body:
        if not isinstance(stmt, ast.Assign):
            continue
        if len(stmt.targets) != 1 or not isinstance(stmt.targets[0], ast.Name):
            continue
        var = stmt.targets[0].id
        val = stmt.value
        cast = _cast_name(val)
        if cast:
            val = val.args[0] if val.args else val
        if _is_params_get(val):
            _, default = _extract_params_get(val)
            if cast:
                t = cast
                if default is not None:
                    try:
                        default = __builtins__[cast](default) if isinstance(__builtins__, dict) else getattr(__import__("builtins"), cast)(default)
                    except Exception:
                        pass
            else:
                t = _infer_type(var, default)
            result[var] = (t, default if default is not None else (False if t == "bool" else ("" if t == "str" else 0)))
    return result


def _extract_invest_args_dict(func_body: list, local_vars: dict) -> dict[str, ToolParam]:
    """
    Parse the invest_args = { ... } literal in the function body.
    Returns {invest_key: ToolParam}.
    """
    params: dict[str, ToolParam] = {}

    def _process_dict(d: ast.Dict):
        for k_node, v_node in zip(d.keys, d.values):
            if not isinstance(k_node, ast.Constant):
                continue
            invest_key = k_node.value
            if invest_key in ("workspace_dir",):
                continue
            _add_entry(invest_key, v_node)

    def _add_entry(invest_key: str, v_node, optional_override: bool = False):
        cast = _cast_name(v_node)
        inner = v_node.args[0] if cast and v_node.args else v_node

        # params["key"] → required  (but only required if NOT inside an if-block)
        if _is_params_subscript(inner):
            t = cast if cast else _infer_type(invest_key, None)
            if optional_override:
                default = "" if t == "str" else (False if t == "bool" else 0)
                params[invest_key] = ToolParam(
                    name=invest_key, type_hint=t, default=default, required=False
                )
            else:
                params[invest_key] = ToolParam(
                    name=invest_key, type_hint=t, default=None, required=True
                )
            return

        # params.get("key", default) → optional
        if _is_params_get(inner):
            _, default = _extract_params_get(inner)
            if cast:
                t = cast
            else:
                t = _infer_type(invest_key, default)
            if default is None:
                default = "" if t == "str" else (False if t == "bool" else 0)
            params[invest_key] = ToolParam(
                name=invest_key, type_hint=t, default=default, required=False
            )
            return

        # Local variable reference (e.g., cc_method, do_valuation)
        if isinstance(inner, ast.Name) and inner.id in local_vars:
            t, default = local_vars[inner.id]
            params[invest_key] = ToolParam(
                name=invest_key, type_hint=t, default=default, required=False
            )
            return

        # Constant literal (hardcoded value — skip as a function param)
        val = _const(inner)
        if val is not None:
            # Still add it as optional so Claude can override if needed
            t = _infer_type(invest_key, val)
            params[invest_key] = ToolParam(
                name=invest_key, type_hint=t, default=val, required=False
            )

    # Find invest_args = { ... } assignment
    for stmt in func_body:
        if isinstance(stmt, ast.Assign):
            for target in stmt.targets:
                if isinstance(target, ast.Name) and target.id == "invest_args":
                    if isinstance(stmt.value, ast.Dict):
                        _process_dict(stmt.value)

    # Also look for invest_args.update({ ... }) calls and conditional additions
    for stmt in func_body:
        # invest_args.update({...})
        if (isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Call)):
            call = stmt.value
            if (isinstance(call.func, ast.Attribute)
                    and call.func.attr == "update"
                    and isinstance(call.func.value, ast.Name)
                    and call.func.value.id == "invest_args"):
                if call.args and isinstance(call.args[0], ast.Dict):
                    _process_dict(call.args[0])

        # if <cond>: invest_args["key"] = params.get(...)  → all optional
        if isinstance(stmt, ast.If):
            for sub in ast.walk(stmt):
                if isinstance(sub, ast.Assign):
                    for tgt in sub.targets:
                        if (isinstance(tgt, ast.Subscript)
                                and isinstance(tgt.value, ast.Name)
                                and tgt.value.id == "invest_args"):
                            key_node = tgt.slice
                            if isinstance(key_node, ast.Constant):
                                _add_entry(key_node.value, sub.value, optional_override=True)
                # invest_args.update inside if block → all optional
                if (isinstance(sub, ast.Expr) and isinstance(sub.value, ast.Call)):
                    call = sub.value
                    if (isinstance(call.func, ast.Attribute)
                            and call.func.attr == "update"
                            and isinstance(call.func.value, ast.Name)
                            and call.func.value.id == "invest_args"):
                        if call.args and isinstance(call.args[0], ast.Dict):
                            # Walk dict entries with optional_override
                            d = call.args[0]
                            for k_node, v_node in zip(d.keys, d.values):
                                if isinstance(k_node, ast.Constant) and k_node.value != "workspace_dir":
                                    _add_entry(k_node.value, v_node, optional_override=True)

        # Pattern: for opt_key in ("key1", "key2", ...):
        #               if params.get(opt_key): invest_args[opt_key] = params[opt_key]
        # → add all keys in the tuple as optional str params
        if isinstance(stmt, ast.For):
            iter_node = stmt.iter
            if isinstance(iter_node, ast.Tuple):
                opt_keys = [
                    elt.value for elt in iter_node.elts
                    if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
                ]
                for opt_key in opt_keys:
                    if opt_key not in params:
                        t = _infer_type(opt_key, None)
                        default = "" if t == "str" else (False if t == "bool" else 0)
                        params[opt_key] = ToolParam(
                            name=opt_key, type_hint=t, default=default, required=False
                        )

    return params


def _extract_all_params_from_body(func_body: list, required_keys: set[str]) -> dict[str, ToolParam]:
    """For custom (non-InVEST) tools: extract params from the full function body.

    Finds every ``params["key"]`` (required) and ``params.get("key", dflt)``
    (optional) anywhere in the function, then cross-checks against REQUIRED_KEYS.
    """
    params: dict[str, ToolParam] = {}

    for node in ast.walk(ast.Module(body=func_body, type_ignores=[])):
        # params.get("key", default) — check before the subscript pattern
        if _is_params_get(node):
            key, default = _extract_params_get(node)
            if not key or key in params:
                continue
            t = _infer_type(key, default)
            if default is None:
                default = "" if t == "str" else (False if t == "bool" else 0)
            params[key] = ToolParam(name=key, type_hint=t, default=default, required=False)

        # params["key"] — subscript access → required by default
        elif _is_params_subscript(node):
            key_node = node.slice
            if not isinstance(key_node, ast.Constant) or not isinstance(key_node.value, str):
                continue
            key = key_node.value
            if key in params:
                continue
            t = _infer_type(key, None)
            params[key] = ToolParam(name=key, type_hint=t, default=None, required=True)

    # Re-reconcile requiredness against REQUIRED_KEYS list:
    # anything in REQUIRED_KEYS is definitely required;
    # anything NOT in REQUIRED_KEYS (but was params["key"]) stays required
    # only if REQUIRED_KEYS itself was empty (no explicit list defined).
    if required_keys:
        for key in list(params.keys()):
            p = params[key]
            should_be_req = key in required_keys
            if should_be_req and not p.required:
                params[key] = ToolParam(name=key, type_hint=p.type_hint,
                                        default=None, required=True)
            elif not should_be_req and p.required:
                t = p.type_hint
                params[key] = ToolParam(name=key, type_hint=t,
                                        default="" if t == "str" else (False if t == "bool" else 0),
                                        required=False)

    return params


def _find_async_run_function(tree: ast.Module) -> Optional[ast.AsyncFunctionDef]:
    for node in ast.walk(tree):
        if isinstance(node, ast.AsyncFunctionDef) and node.name.startswith("run_"):
            return node
    return None


def _model_name_from_function(fn_name: str) -> str:
    """'run_coastal_blue_carbon' → 'Coastal Blue Carbon'"""
    shortcuts = {
        "cbc_main":        "Coastal Blue Carbon",
        "cbc_preprocessor": "Coastal Blue Carbon Preprocessor",
        "ndr":             "Nutrient Delivery Ratio",
        "sdr":             "Sediment Delivery Ratio",
        "hra":             "Habitat Risk Assessment",
        "routedem":        "RouteDEM",
        "delineateit":     "DelineateIt",
    }
    stem = fn_name.removeprefix("run_")
    return shortcuts.get(stem, stem.replace("_", " ").title())


# ---------------------------------------------------------------------------
# Main parse entry point
# ---------------------------------------------------------------------------

def parse_nan_tool(filepath: Path) -> Optional[ToolSpec]:
    """Parse one of Nan's tool files and return a ToolSpec, or None on failure."""
    source = filepath.read_text()
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        print(f"  [SKIP] {filepath.name}: SyntaxError: {e}", file=sys.stderr)
        return None

    func_node = _find_async_run_function(tree)
    if not func_node:
        print(f"  [SKIP] {filepath.name}: no async run_* function found", file=sys.stderr)
        return None

    fn_name = func_node.name
    invest_module, invest_execute = _extract_invest_module(tree)
    required_keys: set[str] = set(_extract_required_keys(tree))

    is_custom = not bool(invest_module)

    if is_custom:
        # Non-InVEST tool: walk the whole function body for params["key"] /
        # params.get() patterns instead of an invest_args dict.
        raw_params = _extract_all_params_from_body(func_node.body, required_keys)
    else:
        local_vars = _collect_local_param_vars(func_node.body)
        raw_params = _extract_invest_args_dict(func_node.body, local_vars)

    # Build ordered param list: required first, optional second
    required_list: list[ToolParam] = []
    optional_list: list[ToolParam] = []
    seen: set[str] = set()

    for key, param in raw_params.items():
        if key == "results_suffix":
            continue
        seen.add(key)
        if param.required:
            required_list.append(param)
        else:
            optional_list.append(param)

    if is_custom:
        # Custom tools manage their own workspace via generate_output_dir();
        # no workspace_dir / results_suffix params needed in the MCP signature.
        pass
    else:
        # workspace_dir and results_suffix are always last for InVEST tools
        optional_list.append(ToolParam("workspace_dir", "str", "", required=False))
        optional_list.append(ToolParam("results_suffix", "str", "", required=False))

    # Detect complex logic that the converter couldn't fully capture
    has_complex = bool(
        required_keys and not any(p.required for p in required_list)
    ) or any(
        isinstance(stmt, ast.If) for stmt in func_node.body
        if not isinstance(stmt, (ast.Expr, ast.Assign, ast.Return, ast.Try))
    )

    raw_docstring = ast.get_docstring(tree) or ""
    doc_description, doc_param_hints = _parse_module_docstring(raw_docstring)

    # doc_summary = first free-text line that is NOT a Tool:/Required:/Optional: header
    _skip_prefixes = ("Tool:", "Tool ", "Required:", "Required ", "Optional:", "Optional ")
    doc_summary = ""
    for line in raw_docstring.splitlines():
        s = line.strip()
        if s and not any(s.startswith(p) for p in _skip_prefixes):
            doc_summary = s
            break

    return ToolSpec(
        function_name=fn_name,
        model_name=_model_name_from_function(fn_name),
        output_subdir=fn_name.removeprefix("run_"),
        invest_module=invest_module,
        invest_execute=invest_execute,
        params=required_list + optional_list,
        doc_summary=doc_summary,
        doc_description=doc_description,
        doc_param_hints=doc_param_hints,
        source_file=filepath.name,
        has_complex_logic=has_complex,
        is_custom_tool=is_custom,
    )


# ---------------------------------------------------------------------------
# Model-level descriptions  (used when Nan's docstring has no free-text block)
# Follows Shubham's style: one or two sentences describing what the model does.
# ---------------------------------------------------------------------------
_MODEL_DESCRIPTIONS: dict[str, str] = {
    "run_coastal_vulnerability": (
        "Assesses the relative vulnerability of coastlines to erosion and inundation "
        "based on geomorphology, wave exposure, sea level rise, and habitat protection."
    ),
    "run_scenic_quality": (
        "Quantifies the visual impact of built structures (e.g. wind turbines, cell towers) "
        "on scenic quality across a landscape using viewshed analysis."
    ),
    "run_wave_energy": (
        "Estimates wave energy production potential and, optionally, the economic value "
        "of wave energy devices deployed in coastal waters."
    ),
    "run_offshore_wind_energy": (
        "Maps offshore wind energy potential and estimates energy production, capacity, "
        "and net present value for offshore wind farms."
    ),
    "run_urban_cooling": (
        "Estimates the cooling effect of urban green spaces and calculates associated "
        "energy savings and work productivity benefits from reduced heat exposure."
    ),
    "run_urban_flood": (
        "Models urban flood risk mitigation by estimating runoff retention from green "
        "infrastructure based on curve numbers and storm event depth."
    ),
    "run_urban_nature_access": (
        "Quantifies resident access to urban nature based on the proximity and supply "
        "of green and blue spaces relative to population distribution."
    ),
    "run_urban_mental_health": (
        "Estimates the mental health benefits of urban nature access by combining "
        "green space supply with population exposure metrics."
    ),
    "run_urban_stormwater": (
        "Models urban stormwater retention, runoff, and associated water quality and "
        "economic benefits from green infrastructure and pervious surfaces."
    ),
    "run_delineateit": (
        "Delineates watersheds from a DEM by snapping pour points to the nearest stream "
        "and tracing upstream contributing areas."
    ),
    "run_routedem": (
        "Computes hydrological routing outputs from a DEM — flow direction, flow "
        "accumulation, slope, stream networks, and downstream distance rasters."
    ),
    "run_scenario_gen_proximity": (
        "Generates a modified land use/land cover scenario by converting pixels "
        "nearest or farthest from a focal landcover type up to a specified area target."
    ),
    "run_crop_percentile": (
        "Estimates crop production using globally observed percentile yield datasets, "
        "providing 25th, 50th, and 75th percentile production estimates per crop."
    ),
    "run_urban_flood_risk_mitigation": (
        "Models urban flood risk mitigation by estimating runoff retention provided "
        "by green infrastructure based on curve numbers and design storm depth."
    ),
}


# ---------------------------------------------------------------------------
# Code generator — custom (non-InVEST) async wrapper
# ---------------------------------------------------------------------------

def generate_custom_mcp_tool(spec: ToolSpec) -> str:
    """Generate an async @mcp.tool() that delegates to Nan's tool module.

    The generated function:
      1. Inserts NAN_TOOLS_DIR into sys.path so Nan's module is importable.
      2. Builds the params dict from flat MCP kwargs.
      3. Imports and awaits Nan's async run_* function.
      4. Returns a JSON status envelope.

    The server's .env must define NAN_TOOLS_DIR pointing at Nan's tools/
    directory and any config variables that shared/utils.py needs
    (e.g. OUTPUT_BASE_DIR for generate_output_dir).
    """
    lines: list[str] = []

    eq = "=" * 68
    lines.append(f"# {eq}")
    lines.append(f"# {spec.model_name}")
    lines.append(f"# (auto-generated from {spec.source_file} by nan_to_mcp.py)")
    lines.append(f"# {eq}")
    lines.append("@mcp.tool()")

    required_params = [p for p in spec.params if p.required]
    optional_params = [p for p in spec.params if not p.required]

    sig_parts: list[str] = []
    for p in required_params:
        sig_parts.append(f"    {p.name}: {p.type_hint}")
    for p in optional_params:
        dv = _default_repr(p.type_hint, p.default)
        sig_parts.append(f"    {p.name}: {p.type_hint} = {dv}")

    if sig_parts:
        sig = "async def {}(\n{},\n) -> str:".format(
            spec.function_name,
            ",\n".join(sig_parts),
        )
    else:
        sig = f"async def {spec.function_name}() -> str:"
    lines.append(sig)

    # Docstring
    official = INVEST_DOCS.get(spec.function_name, {})
    opening = (official.get("description", "").strip()
                or spec.doc_description
                or spec.doc_summary
                or f"Run the {spec.model_name} tool.")
    wrapped = textwrap.fill(opening, width=75, subsequent_indent="    ")
    doc: list[str] = [f'    """{wrapped}', ""]
    all_params = required_params + optional_params
    if all_params:
        doc.append("    Args:")
        official_params: dict[str, str] = official.get("params", {})
        for p in all_params:
            if p.name in official_params:
                desc = official_params[p.name]
            elif p.name in _PARAM_DESCRIPTIONS:
                desc = _PARAM_DESCRIPTIONS[p.name]
            elif spec.doc_param_hints.get(p.name):
                desc = spec.doc_param_hints[p.name]
            else:
                desc = p.name.replace("_", " ").title()
            doc.append(f"        {p.name}: {desc}")
    doc.append('    """')
    lines.append("\n".join(doc))

    # Module stem for import (strip .py from source_file)
    stem = spec.source_file[:-3] if spec.source_file.endswith(".py") else spec.source_file

    # Body
    lines.append("    import importlib as _imp, sys as _sys, uuid as _uuid")
    lines.append("")
    lines.append('    _tools_dir = os.getenv("NAN_TOOLS_DIR", "")')
    lines.append("    if _tools_dir and _tools_dir not in _sys.path:")
    lines.append("        _sys.path.insert(0, _tools_dir)")
    lines.append("")
    # Build params dict — pass ALL args; Nan's tool ignores extra optional empty strings
    lines.append("    _params = {")
    for p in all_params:
        lines.append(f'        "{p.name}": {p.name},')
    lines.append("    }")
    lines.append("")
    lines.append(f'    _mod = _imp.import_module("{stem}")')
    lines.append(f'    _fn  = getattr(_mod, "{spec.function_name}")')
    lines.append("    _sid = _uuid.uuid4().hex[:8]")
    lines.append("    _tid = _uuid.uuid4().hex[:8]")
    lines.append("    _cb  = lambda pct, msg: logger.info(\"[%d%%] %s\", pct, msg)")
    lines.append("")
    lines.append("    _start = time.time()")
    lines.append("    try:")
    lines.append("        _result = await _fn(_params, _sid, _tid, _cb)")
    lines.append("        _elapsed = round(time.time() - _start, 2)")
    lines.append(
        f'        return json.dumps({{"status": "success", "model": "{spec.model_name}",'
        f' "elapsed_seconds": _elapsed, **_result}}, indent=2, default=str)'
    )
    lines.append("    except Exception as _e:")
    lines.append("        _elapsed = round(time.time() - _start, 2)")
    lines.append("        logger.error(\"%s failed: %s\", \"" + spec.model_name + "\", _e)")
    lines.append(
        f'        return json.dumps({{"status": "error", "model": "{spec.model_name}",'
        f' "error": str(_e), "elapsed_seconds": _elapsed}}, indent=2)'
    )

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Code generator — InVEST tools
# ---------------------------------------------------------------------------

def generate_mcp_tool(spec: ToolSpec) -> str:
    """Render a complete @mcp.tool() decorated function from a ToolSpec."""
    if spec.is_custom_tool:
        return generate_custom_mcp_tool(spec)
    lines: list[str] = []

    # Section header
    eq = "=" * 68
    lines.append(f"# {eq}")
    lines.append(f"# {spec.model_name}")
    lines.append(f"# (auto-generated from {spec.source_file} by nan_to_mcp.py)")
    if spec.has_complex_logic:
        lines.append(
            "# ⚠ REVIEW: source has conditional param logic — verify args dict below"
        )
    lines.append(f"# {eq}")

    # Decorator
    lines.append("@mcp.tool()")

    # Function signature
    required_params = [p for p in spec.params if p.required]
    optional_params = [p for p in spec.params if not p.required]

    sig_parts: list[str] = []
    for p in required_params:
        sig_parts.append(f"    {p.name}: {p.type_hint}")
    for p in optional_params:
        dv = _default_repr(p.type_hint, p.default)
        sig_parts.append(f"    {p.name}: {p.type_hint} = {dv}")

    if sig_parts:
        sig = "def {}(\n{},\n) -> str:".format(
            spec.function_name,
            ",\n".join(sig_parts)
        )
    else:
        sig = f"def {spec.function_name}() -> str:"
    lines.append(sig)

    # ── Docstring ─────────────────────────────────────────────────────────────
    # Priority for the opening summary:
    #   1. Official readthedocs description  (from invest_docs_cache.json)
    #   2. Curated _MODEL_DESCRIPTIONS entry
    #   3. Free-text extracted from Nan's module docstring
    #   4. First non-header line of Nan's module docstring
    #   5. Generic fallback
    official = INVEST_DOCS.get(spec.function_name, {})
    official_desc = official.get("description", "").strip()
    official_params: dict[str, str] = official.get("params", {})

    if official_desc:
        opening = official_desc
    elif spec.function_name in _MODEL_DESCRIPTIONS:
        opening = _MODEL_DESCRIPTIONS[spec.function_name]
    elif spec.doc_description:
        opening = spec.doc_description
    elif spec.doc_summary:
        opening = spec.doc_summary
    else:
        opening = f"Run the InVEST {spec.model_name} model."

    # Wrap to 79 chars for the summary paragraph
    wrapped = textwrap.fill(opening, width=75, subsequent_indent="    ")
    doc: list[str] = [f'    """{wrapped}', ""]

    # Per-param description helper — four-layer priority:
    #   1. Official readthedocs docs  (official_params from cache)
    #   2. Curated _PARAM_DESCRIPTIONS lookup
    #   3. Nan's Optional: hint from module docstring
    #   4. Name-pattern fallback
    def _param_desc(p: ToolParam) -> str:
        # 1. Official readthedocs description (highest authority)
        if p.name in official_params:
            return official_params[p.name]

        # 2. Curated hand-written lookup
        if p.name in _PARAM_DESCRIPTIONS:
            base = _PARAM_DESCRIPTIONS[p.name]
            hint = spec.doc_param_hints.get(p.name, "")
            if hint and hint.lower() not in base.lower():
                if "|" in hint or hint.startswith("'") or re.match(r"^[a-z]", hint):
                    base = f"{base} ({hint})"
            return base

        # 3. Nan's Optional: hint
        hint = spec.doc_param_hints.get(p.name, "")
        if hint:
            return hint[0].upper() + hint[1:]

        # 4. Name-pattern fallback
        name = p.name
        if name.endswith("_raster_path"):
            return f"Path to {name[:-12].replace('_', ' ')} raster"
        if name.endswith("_vector_path"):
            return f"Path to {name[:-12].replace('_', ' ')} vector"
        if name.endswith("_table_path"):
            return f"Path to {name[:-11].replace('_', ' ')} CSV table"
        if name.endswith("_path"):
            return f"Path to {name[:-5].replace('_', ' ')} file"
        if name.endswith("_csv"):
            return f"Path to {name[:-4].replace('_', ' ')} CSV"
        if name.endswith("_dir"):
            return f"Path to {name[:-4].replace('_', ' ')} directory"
        if name.startswith("do_") or name.startswith("use_") or name.startswith("calc_"):
            return f"If True, {name.split('_', 1)[1].replace('_', ' ')}"
        if name.startswith("calculate_"):
            return f"If True, compute {name[10:].replace('_', ' ')} raster"
        dv = _default_repr(p.type_hint, p.default)
        return f"Required {p.type_hint}" if p.required else f"Optional {p.type_hint}, default {dv}"

    doc.append("    Args:")
    for p in spec.params:
        desc = _param_desc(p)
        # Wrap long descriptions at 79 chars
        line = f"        {p.name}: {desc}"
        if len(line) > 88:
            wrapped_desc = textwrap.fill(
                desc, width=75,
                initial_indent=f"        {p.name}: ",
                subsequent_indent="            ",
            )
            doc.append(wrapped_desc)
        else:
            doc.append(line)

    doc.append('    """')
    lines.append("\n".join(doc))

    # Import
    if spec.invest_module:
        lines.append(f"    import {spec.invest_module}")

    lines.append("")

    # Workspace
    lines.append(
        f'    ws = ensure_workspace(workspace_dir, os.path.join(OUTPUT_DIR, "{spec.output_subdir}"))'
    )

    # Build args dict
    args_lines = ["    args = {"]
    for p in spec.params:
        if p.name in ("workspace_dir", "results_suffix"):
            continue
        args_lines.append(f'        "{p.name}": {p.name},')
    args_lines.append('        "workspace_dir": ws,')
    args_lines.append('        "results_suffix": results_suffix,')
    args_lines.append("    }")
    lines.append("\n".join(args_lines))

    # Execute via run_invest_model helper
    lines.append("")
    if spec.invest_module:
        lines.append(
            f'    return run_invest_model("{spec.model_name}", {spec.invest_module}, args, ws)'
        )
    else:
        # Non-InVEST tool: emit a stub body that raises so Nan can fill it in
        lines.append(f'    # ⚠ TODO: {spec.source_file} has no natcap.invest import.')
        lines.append(f'    # Replace this stub with the real implementation.')
        lines.append(f'    raise NotImplementedError("{spec.function_name} requires a custom implementation — see {spec.source_file}")')

    return "\n".join(lines) + "\n"


def generate_stub(filepath: Path) -> str:
    """For non-InVEST utilities, emit a commented stub."""
    fn_name = filepath.stem
    if not fn_name.startswith("run_"):
        fn_name = f"run_{fn_name}"
    return textwrap.dedent(f"""\
        # {'='*68}
        # {fn_name}  ← NON-InVEST utility
        # Source: {filepath.name}
        # This module does not use natcap.invest — implement manually.
        # {'='*68}
        # @mcp.tool()
        # def {fn_name}(...) -> str:
        #     \"\"\"TODO: implement from {filepath.name}\"\"\"
        #     ...

    """)


# ---------------------------------------------------------------------------
# Driver — helpers
# ---------------------------------------------------------------------------

def _fn_name_for_stem(stem: str) -> str:
    """Map a tool file stem to its expected MCP function name."""
    return {"cbc_main": "run_coastal_blue_carbon",
            "cbc_preprocessor": "run_coastal_blue_carbon_preprocessor"}.get(stem, f"run_{stem}")


def _param_signature(node: ast.FunctionDef) -> tuple:
    """Return a comparable representation of a function's parameter list.

    Captures (name, annotation_str, default_str) for every argument so that
    any change Nan makes — adding/removing a param, changing a type hint or
    default value — is detected as a signature difference.
    """
    # Pad defaults to align with args (defaults cover the *last* N args)
    n_args = len(node.args.args)
    n_defs = len(node.args.defaults)
    pad = n_args - n_defs
    defaults = [None] * pad + node.args.defaults

    rows = []
    for arg, default in zip(node.args.args, defaults):
        ann = ast.unparse(arg.annotation) if arg.annotation else ""
        dfl = ast.unparse(default)        if default    else ""
        rows.append((arg.arg, ann, dfl))
    return tuple(rows)


def _server_signatures(path: Path) -> dict[str, tuple]:
    """Return {fn_name: _param_signature()} for every run_* function in path."""
    sigs: dict[str, tuple] = {}
    try:
        tree = ast.parse(path.read_text())
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("run_"):
                sigs[node.name] = _param_signature(node)
    except Exception:
        pass
    return sigs


def _existing_tools_in_file(path: Path) -> set[str]:
    """Return the set of run_* function names defined in path."""
    return set(_server_signatures(path).keys())


def _replace_in_server(server_path: Path, fn_name: str, new_code: str) -> bool:
    """Replace the existing @mcp.tool() function *fn_name* in server_path
    with *new_code*, including its preceding section-header comment block.

    Uses Python 3.8+ ``end_lineno`` AST attribute for exact line boundaries.
    Returns True if the replacement was made, False if the function was not found.
    """
    source = server_path.read_text()
    lines  = source.splitlines(keepends=True)

    try:
        tree = ast.parse(source)
    except SyntaxError:
        return False

    for node in ast.walk(tree):
        if not (isinstance(node, ast.FunctionDef) and node.name == fn_name):
            continue

        # --- locate decorator / function boundaries (1-indexed AST → 0-indexed slice) ---
        dec_line0 = (node.decorator_list[0].lineno - 1
                     if node.decorator_list else node.lineno - 1)
        end_line0 = node.end_lineno   # 1-indexed inclusive → 0-indexed exclusive

        # --- walk backward to absorb the section-header comment block ---
        # We accept blank lines and comment lines; stop on any other content.
        block_start = dec_line0
        for i in range(dec_line0 - 1, max(-1, dec_line0 - 20), -1):
            stripped = lines[i].strip()
            if stripped == "" or stripped.startswith("#"):
                block_start = i
            else:
                break

        # --- replace the block with the new code ---
        replacement = new_code.rstrip("\n") + "\n\n"
        lines[block_start:end_line0] = [replacement]
        server_path.write_text("".join(lines))
        return True

    return False


def _signature_diff(old_sig: tuple, new_sig: tuple) -> str:
    """Return a human-readable one-line description of what changed."""
    old_names = {r[0] for r in old_sig}
    new_names = {r[0] for r in new_sig}
    added   = new_names - old_names
    removed = old_names - new_names
    changed = {r[0] for r in new_sig if r[0] in old_names
               and r != next((o for o in old_sig if o[0] == r[0]), None)}
    parts = []
    if added:   parts.append(f"+{{{', '.join(sorted(added))}}}")
    if removed: parts.append(f"-{{{', '.join(sorted(removed))}}}")
    if changed: parts.append(f"~{{{', '.join(sorted(changed))}}}")
    return "  ".join(parts) if parts else "default or type changed"


# ---------------------------------------------------------------------------
# Driver — main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert Nan's async tool modules to FastMCP @mcp.tool() functions.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "source",
        help="Path to a single Nan tool .py file OR a directory of tool modules.",
    )
    parser.add_argument(
        "--output", "-o",
        metavar="FILE",
        help="Write generated code to FILE instead of stdout.",
    )
    parser.add_argument(
        "--append-to", "-a",
        metavar="SERVER_PY",
        help=(
            "Append NEW tools to an existing server.py. "
            "Existing tools are skipped even if their signatures changed. "
            "Use --sync to also update changed tools."
        ),
    )
    parser.add_argument(
        "--sync",
        metavar="SERVER_PY",
        help=(
            "Full sync against an existing server.py:\n"
            "  • NEW tool    → appended before the entry-point block\n"
            "  • CHANGED tool → replaced in-place (signature diff shown)\n"
            "  • UNCHANGED   → skipped\n"
            "Use --dry-run to preview without writing."
        ),
    )
    parser.add_argument(
        "--skip", "-s",
        nargs="*",
        metavar="STEM",
        default=[],
        help="Module stems to skip (e.g. --skip cbc_main habitat_quality).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would change without writing any file.",
    )
    parser.add_argument(
        "--include-duplicates",
        action="store_true",
        help="Also convert tools already present in the default ALREADY_IN_SERVER list.",
    )
    args = parser.parse_args()

    if args.append_to and args.sync:
        sys.exit("ERROR: --append-to and --sync are mutually exclusive.")

    source = Path(args.source).expanduser().resolve()

    # Collect input files
    if source.is_file():
        files = [source]
    elif source.is_dir():
        files = sorted(source.glob("*.py"))
        files = [f for f in files if f.name != "__init__.py"]
    else:
        sys.exit(f"ERROR: {source} is not a file or directory.")

    # Determine target server path and current signatures
    server_path: Optional[Path] = None
    existing_sigs: dict[str, tuple] = {}
    existing_names: set[str] = set()

    if args.append_to:
        server_path = Path(args.append_to).expanduser()
        existing_names = _existing_tools_in_file(server_path)
        print(f"[info] {len(existing_names)} tools already in {args.append_to}", file=sys.stderr)

    if args.sync:
        server_path = Path(args.sync).expanduser()
        existing_sigs  = _server_signatures(server_path)
        existing_names = set(existing_sigs.keys())
        print(f"[info] {len(existing_names)} tools in {args.sync} (sync mode)", file=sys.stderr)

    skip_stems: set[str] = set(args.skip)

    # ── Convert each file ────────────────────────────────────────────────────
    # append mode:  new_blocks → appended to server
    # sync mode:    new_blocks → appended;  updated_tools → replaced in-place
    new_blocks:      list[str]        = []   # code blocks to append
    updated_tools:   dict[str, str]   = {}   # fn_name → new code (sync mode only)
    dry_run_changes: int              = 0    # counter for dry-run reporting
    skipped:         list[str]        = []
    failed:          list[str]        = []

    for filepath in files:
        stem = filepath.stem

        if stem.startswith("_") or stem in ("utils", "config", "server"):
            continue

        fn_name = _fn_name_for_stem(stem)

        # --- static skip list ---
        if stem in skip_stems:
            skipped.append(f"  --skip:         {filepath.name}")
            continue
        if not args.include_duplicates and fn_name in ALREADY_IN_SERVER:
            if not args.sync:          # in sync mode we still want to update these
                skipped.append(f"  already in MCP: {filepath.name}")
                continue

        # --- append mode: skip if already in target ---
        if args.append_to and fn_name in existing_names:
            skipped.append(f"  already exists: {filepath.name}  (use --sync to update)")
            continue

        if args.dry_run and not args.sync:
            print(f"  would add: {filepath.name} → {fn_name}()")
            continue

        # --- generate the new tool code ---
        spec = parse_nan_tool(filepath)
        if spec is None:
            failed.append(filepath.name)
            continue
        block = generate_mcp_tool(spec)

        # --- sync mode: classify as new / changed / unchanged ---
        if args.sync:
            if fn_name not in existing_names:
                # Brand-new tool
                if args.dry_run:
                    print(f"  [+] {filepath.name} → {fn_name}()  (new, would append)")
                    dry_run_changes += 1
                    continue
                new_blocks.append(block)
                flag = " ⚠" if (not isinstance(stem, str) or
                                  getattr(spec, 'has_complex_logic', False)) else ""
                print(f"  [+]{flag} {filepath.name} → appended", file=sys.stderr)
            else:
                # Tool already exists — compare signatures
                _parsed_block = ast.parse(block)
                new_sig = _param_signature(next(
                    n for n in ast.walk(_parsed_block)
                    if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and n.name == fn_name
                ))
                old_sig = existing_sigs[fn_name]

                if new_sig == old_sig:
                    skipped.append(f"  [=] {filepath.name}  (unchanged)")
                    continue

                diff_desc = _signature_diff(old_sig, new_sig)
                if args.dry_run:
                    print(f"  [~] {filepath.name} → {fn_name}()  CHANGED: {diff_desc}")
                    dry_run_changes += 1
                    continue

                updated_tools[fn_name] = block
                print(f"  [~] {filepath.name} → {fn_name}()  updated ({diff_desc})", file=sys.stderr)
            continue

        # --- append / output mode ---
        new_blocks.append(block)
        kind = "async/custom" if getattr(spec, "is_custom_tool", False) else "invest"
        flag = " ⚠ review" if getattr(spec, "has_complex_logic", False) else ""
        print(f"  [ok]{flag} [{kind}]  {filepath.name} → {fn_name}()", file=sys.stderr)

    if args.dry_run:
        if dry_run_changes == 0:
            print("[dry-run] nothing to change")
        else:
            print(f"[dry-run] {dry_run_changes} change(s) would be applied — rerun without --dry-run to apply")
        return

    # ── Apply changes ────────────────────────────────────────────────────────

    # 1. In-place replacements (sync mode)
    if updated_tools and server_path:
        for fn_name, new_code in updated_tools.items():
            ok = _replace_in_server(server_path, fn_name, new_code)
            if not ok:
                print(f"  [WARN] could not locate {fn_name} in {server_path}", file=sys.stderr)
        print(f"[sync] Replaced {len(updated_tools)} tool(s) in {server_path}", file=sys.stderr)

    # 2. Append new tools
    if new_blocks:
        header = textwrap.dedent(f"""\
            # ============================================================
            # AUTO-GENERATED by nan_to_mcp.py
            # Source: {source}
            # Run `python nan_to_mcp.py --help` to regenerate.
            # Review all ⚠ sections before deploying.
            # ============================================================

        """)
        full_output = header + "\n\n".join(new_blocks)

        if server_path:  # --append-to or --sync
            server_text = server_path.read_text()
            marker = '\nif __name__ == "__main__":'
            if marker in server_text:
                pos = server_text.index(marker)
                new_text = server_text[:pos] + "\n\n" + full_output + server_text[pos:]
            else:
                new_text = server_text + "\n\n" + full_output
            server_path.write_text(new_text)
            print(f"[done] Appended {len(new_blocks)} new tool(s) to {server_path}", file=sys.stderr)

        elif args.output:
            out_path = Path(args.output).expanduser()
            out_path.write_text(full_output)
            print(f"[done] Wrote {len(new_blocks)} tool(s) to {args.output}", file=sys.stderr)

        else:
            print(full_output)

    elif not updated_tools:
        print("[info] Nothing to generate.", file=sys.stderr)

    # ── Summary ──────────────────────────────────────────────────────────────
    if skipped:
        print(f"\n[skipped {len(skipped)}]", file=sys.stderr)
        for s in skipped:
            print(s, file=sys.stderr)
    if failed:
        print(f"\n[failed  {len(failed)}]", file=sys.stderr)
        for f in failed:
            print(f"  {f}", file=sys.stderr)


if __name__ == "__main__":
    main()
